{% set name = "stringparser" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stringparser-{{ version }}.tar.gz
  sha256: 6ed01aa00644c939baf3e4df1cfcfae36480619ac01c6c82aa93c797f29d0d19

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - stringparser
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/hgrecco/stringparser
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Easy to use pattern matching and information extraction

  description: |
    The stringparser module provides a simple way to match patterns and
    extract information within strings. As patterns are given using the
    familiar format string specification PEP 3101, writing them is much
    easier than writing regular expressions (albeit less powerful).
  dev_url: https://github.com/hgrecco/stringparser

extra:
  recipe-maintainers:
    - mtsolmn
